name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIRECTORY: build
  DOCKER_IMAGE_NAME: cpp-hostpath

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Code
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/${{env.BUILD_DIRECTORY}} --config ${{env.BUILD_TYPE}} -j
      
    - name: Get Build Version 
      run: echo "VERSION=$(${{github.workspace}}/${{env.BUILD_DIRECTORY}}/hostpath --version)" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.HOSTPATH_IMAGE_BUILD_SECRET }}
        
    - name: Build Docker image
      run: docker build . --tag ghcr.io/sawantshivaji1997/${{env.DOCKER_IMAGE_NAME}}:${{env.VERSION}}
        
    - name: Retag Image
      if: ${{ env.VERSION == '0.0.0' }}
      run: docker tag ghcr.io/sawantshivaji1997/${{env.DOCKER_IMAGE_NAME}}:${{env.VERSION}} ghcr.io/sawantshivaji1997/${{env.DOCKER_IMAGE_NAME}}:latest
        
    - name: Push Docker Image
      run: docker push ghcr.io/sawantshivaji1997/${{env.DOCKER_IMAGE_NAME}}:${{env.VERSION}}
